version: 2
jobs:
  build:
    working_directory: /usr/src/app
    docker:
      - image: node
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: package-{{ checksum "package-lock.json" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: NODE_ENV=dev npm install --package-lock && npm audit fix

      # Keep cache
      - save_cache:
          key: package-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

      # Test
      - run:
          name: Tests
          command: npm test

      # Coverage
      - run:
          name: Coverage
          command: yarn codecov

